version: 2

jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.7.3
        environment:
          MIX_ENV: test

    working_directory: ~/app

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - v0.1.2-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v0.1.2-mix-cache-{{ .Branch }}
            - v0.1.2-mix-cache
      - restore_cache:
          keys:
            - v0.1.2-build-cache-{{ .Branch }}
            - v0.1.2-build-cache
      - run: mix do deps.get --only test, compile --warning-as-errors
      - save_cache:
          key: v0.1.2-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v0.1.2-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v0.1.2-mix-cache
          paths: "deps"
      - save_cache:
          key: v0.1.2-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v0.1.2-build-cache
          paths: "_build"
      - run: mix coveralls.circle
      - run: mix format --check-formatted
      - run: mix credo --strict --ignore moduledoc
